titulo: Nua Mana | Guias y Scouts
nombre: Guias y Scouts Nua Mana
address:
  city: Santiago
  commune: La Granja
  country: Chile
  institution: Colegio
  street: San José de la Estrella 0857
  zip: '8801000'
encuentranos:
  comuna_de: La Granja
  nos_encontraras_todos_los: sábados desde las 15.00 hrs
  nuestro_grupo_trabaja_en: el Colegio Nuestra Señora de Guadalupe
  ubicado_en: San José de la Estrella 0857
