titulo: 'Nua Mana | Guias y Scouts'
nombre: 'Guias y Scouts Nua Mana'
address: 
  institution: 'Colegio Nuestra Señora de Guadalupe'
  street: 'San Jose de la Estrella 0857'
  commune: 'La Granja'
  city: 'Santiago'
  country: 'Chile'
  zip: '8801000'
email: contacto@nuamana.com
descripcion: >
  Guias y Scouts Nua Mana, una nueva aventura, nuestro grupo se encuentra en la comuna de La Granja, 
  Region Metropolitana, Chile. Buscamos el desarrollo de niños y jovenes, mediante el empoderamiento, 
  la ciudadania activa, valores y habilidades para la vida, y una educación para la paz.
resumen: 'Guias y Scouts Nua Mana - una nueva aventura - nuestro grupo se encuentra en la comuna de La Granja buscamos el desarrollo de niños y jovenes mediante el empoderamiento la ciudadania activa valores y habilidades para la vida y una educación para la paz.'
tel: '+56966896001'
tel_display: '+56 ( 9 ) 6689 6001'
encabezado_rongorongo: 'Guias y Scouts Nua Mana Una Nueva Aventura'
frase_fuerza: 'SCOUTS, EDUCACIÓN PARA LA VIDA'
mision: >
  Nuestra misión es contribuir a la educación de jóvenes para que participen en la construcción de un mundo mejor, donde las personas se desarrollen plenamente y jueguen un papel constructivo en la sociedad.
  Mediante un sistema de valores basado en principios espirituales, sociales y personales, que se expresan en la Ley y la Promesa.
mapa: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3324.9125945749147!2d-70.62037978462756!3d-33.555647210305395!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662d0a6e457520d%3A0xc3892aa7fa7d74b!2sGuias+y+Scouts+Nua+Mana!5e0!3m2!1ses-419!2scl!4v1519871070228'
encuentranos:
  nuestro_grupo_trabaja_en: 'el Colegio Nuestra Señora de Guadalupe'
  ubicado_en: 'San José de la Estrella 0857'
  comuna_de: 'La Granja'
  nos_encontraras_todos_los: 'sábados desde las 15.00 hrs'

redes_sociales:
  twitter: 'https://twitter.com/gruponuamana'
  facebook: 'https://www.facebook.com/gruponuamana/'
  google_plus: 'https://plus.google.com/+nuamana'
  instagram: 'https://www.instagram.com/nua_mana/'
  whatsapp: '+56966896001'
