backend:
  name: github
  repo: claudiomateluna/nua_mana
  branch: gh-pages

media_folder: 'assets/images/uploads'
logo_url: '/assets/images/brand.svg'

collections:
  - name: 'configuracion_general'
    label: 'Configuración General'
    description: 'Configuración general del sitio web y de la pagina de inicio, como su nombre, dirección física, Redes Sociales, etc.'
    files:
      - name: 'site'
        label: 'Sitio'
        file: '_data/site.yml'
        fields:
          - label: 'Titulo'
            name: 'titulo'
            widget: 'string'
            hint: 'Titulo del Sitio Web'
          - label: 'Nombre'
            name: 'nombre'
            widget: 'string'
            hint: 'Nombre del grupo Scout'
          - label: 'Dirección'
            name: 'address'
            widget: 'object'
            fields: 
              - label: 'Institución patrocinante'
                name: 'institution'
                widget: 'string'
                hint: 'Nombre de la institución patrocinante que alberga al grupo Scout'
              - label: 'Calle y Numeración'
                name: 'street'
                widget: 'string'
                hint: 'Nombre de la calle y la numeración donde se ubica el grupo'
              - label: 'Comuna'
                name: 'commune'
                widget: 'string'
                hint: 'Comuna donde se ubica el grupo Scout'
              - label: 'Ciudad'
                name: 'city'
                widget: 'string'
                hint: 'Ciudad donde se ubica el grupo Scout'
              - label: 'País'
                name: 'country'
                widget: 'string'
                hint: 'País donde se ubica el grupo Scout'
              - label: 'Código Postal'
                name: 'zip'
                widget: 'string'
          - label: 'Correo Electrónico'
            name: 'email'
            widget: 'string'
            hint: 'Correo Electrónico oficial del grupo Scout'
          - label: 'Teléfono de Contacto'
            name: 'tel'
            widget: 'string'
            hint: 'Ingrese el número telefónico sin espacios con formato de whatsapp'
          - label: 'Teléfono para mostrar'
            name: 'tel_display'
            widget: 'string'
            hint: 'Ingrese el número telefónico en formato fácil de leer y con espacios'
          - label: 'Descripción'
            name: 'descripcion'
            widget: 'string'
            hint: 'Descripción del sitio web del grupo Scout (esto es utilizado para SEO del sitio)'
          - label: 'Resumen General'
            name: 'resumen'
            widget: 'string'
            hint: 'resumen del sitio web (esto es utilizado para las publicaciones en redes sociales)'
          - label: 'Encabezado en Rongo rongo'
            name: 'encabezado_rongorongo'
            widget: 'string'
          - label: 'Frase Fuerza'
            name: 'frase_fuerza'
            widget: 'string'
          - label: 'encuentranos'
            name: 'encuentranos'
            widget: 'object'
            fields: 
              - label: 'Nuestro grupo trabaja en'
                name: 'nuestro_grupo_trabaja_en'
                widget: 'string'
                hint: 'Nombre de la institución patrocinante (utilizado en el mapa dentro de la pagina principal del sitio web)'
              - label: 'Ubicado en'
                name: 'ubicado_en'
                widget: 'string'
                hint: 'Dirección donde realiza sus actividades el grupo Scout (utilizado en el mapa dentro de la pagina principal del sitio web)'
              - label: 'Comuna de'
                name: 'comuna_de'
                widget: 'string'
                hint: 'Comuna donde realiza sus actividades el grupo Scout (utilizado en el mapa dentro de la pagina principal del sitio web)'
              - label: 'Nos encontraras todos los'
                name: 'nos_encontraras_todos_los'
                widget: 'string'
                hint: 'Indique el día y el horario en que comienzan las actividades (utilizado en el mapa dentro de la pagina principal del sitio web)'
          - label: 'Mapa'
            name: 'mapa'
            widget: 'string'
            hint: 'Llave de Google Maps para la ubicación'
          - label: 'Misión'
            name: 'mision'
            widget: 'markdown'
          - label: 'Redes Sociales'
            name: 'redes_sociales'
            widget: 'object'
            fields: 
              - label: 'Twitter'
                name: 'twitter'
                widget: 'string'
                hint: 'Escriba la URL de la red social'
              - label: 'Facebook'
                name: 'facebook'
                widget: 'string'
                hint: 'Escriba la URL de la red social'
              - label: 'Google Plus'
                name: 'google_plus'
                widget: 'string'
                hint: 'Escriba la URL de la red social'
              - label: 'Instagram'
                name: 'instagram'
                widget: 'string'
                hint: 'Escriba la URL de la red social'
              - label: 'Whatsapp'
                name: 'whatsapp'
                widget: 'string'
                hint: 'Escriba el número principal de contacto sin espacios comenzando por +569'
      - name: 'carousel'
        label: 'Carousel de Fotografías'
        file: '_data/carousel.yml'
        fields: 
          - label: 'Logo'
            name: 'logo'
            widget: 'image'
          - label: 'Ancho del Logo'
            name: 'logo_w'
            widget: 'string'
          - label: 'Alto del Logo'
            name: 'logo_h'
            widget: 'string'
          - label: 'Información de la Imagen'
            name: 'logo_alt'
            widget: 'string'
          - label: 'Imagen 1'
            name: '1i'
            widget: 'image'
            hint: 'el alto máximo de la imagen es de 300px'
          - label: 'Ancho de la Imagen 1'
            name: '1w'
            widget: 'string'
          - label: 'Información de la Imagen 1'
            name: '1alt'
            widget: 'string'
          - label: 'Imagen 2'
            name: '2i'
            widget: 'image'
            hint: 'el alto máximo de la imagen es de 300px'
          - label: 'Ancho de la Imagen 2'
            name: '2w'
            widget: 'string'
          - label: 'Información de la Imagen 2'
            name: '2alt'
            widget: 'string'
          - label: 'Imagen 3'
            name: '3i'
            widget: 'image'
            hint: 'el alto máximo de la imagen es de 300px'
          - label: 'Ancho de la Imagen 3'
            name: '3w'
            widget: 'string'
          - label: 'Información de la Imagen 3'
            name: '3alt'
            widget: 'string'
          - label: 'Imagen 4'
            name: '4i'
            widget: 'image'
            hint: 'el alto máximo de la imagen es de 300px'
          - label: 'Ancho de la Imagen 4'
            name: '4w'
            widget: 'string'
          - label: 'Información de la Imagen 4'
            name: '4alt'
            widget: 'string'
          - label: 'Imagen 5'
            name: '5i'
            widget: 'image'
            hint: 'el alto máximo de la imagen es de 300px'
          - label: 'Ancho de la Imagen 5'
            name: '5w'
            widget: 'string'
          - label: 'Información de la Imagen 5'
            name: '5alt'
            widget: 'string'
          - label: 'Imagen 6'
            name: '6i'
            widget: 'image'
            hint: 'el alto máximo de la imagen es de 300px'
          - label: 'Ancho de la Imagen 6'
            name: '6w'
            widget: 'string'
          - label: 'Información de la Imagen 6'
            name: '6alt'
            widget: 'string'
          - label: 'Imagen 7'
            name: '7i'
            widget: 'image'
            hint: 'el alto máximo de la imagen es de 300px'
          - label: 'Ancho de la Imagen 7'
            name: '7w'
            widget: 'string'
          - label: 'Información de la Imagen 7'
            name: '7alt'
            widget: 'string'
      - name: 'nosotros'
        label: 'Tarjetas'
        file: '_data/nosotros.yml'
        fields: 
          - label: 'Palabra Común'
            name: 'frase_comun'
            widget: 'string'
            hint: 'La primera Palabra que será visualizada en las 4 tarjetas de cabecera'
          - label: 'Primera Imagen'
            name: 'imagen1'
            widget: 'image'
            hint: 'El tamaño de la imagen debe ser unicamente de 281px de ancho x 373px de alto'
          - label: 'Primera Palabra'
            name: 'palabra_1'
            widget: 'string'
            hint: 'es la Palabra que aparece debajo de la Palabra Común en la primera tarjeta'
          - label: 'Primera Frase'
            name: 'frase_1'
            widget: 'string'
            hint: 'es la frase que aparece en la parte baja de la tarjeta'
          - label: 'Primera URL'
            name: 'url_1'
            widget: 'string'
            hint: 'es el enlace dentro de nuestra página al que lleva la tarjeta'
          - label: 'Segunda Imagen'
            name: 'imagen2'
            widget: 'image'
            hint: 'El tamaño de la imagen debe ser unicamente de 281px de ancho x 373px de alto'
          - label: 'Segunda Palabra'
            name: 'palabra_2'
            widget: 'string'
            hint: 'es la Palabra que aparece debajo de la Palabra Común en la segunda tarjeta'
          - label: 'Segunda Frase'
            name: 'frase_2'
            widget: 'string'
            hint: 'es la frase que aparece en la parte baja de la tarjeta'
          - label: 'Segunda URL'
            name: 'url_2'
            widget: 'string'
            hint: 'es el enlace dentro de nuestra página al que lleva la tarjeta'
          - label: 'Tercera Imagen'
            name: 'imagen3'
            widget: 'image'
            hint: 'El tamaño de la imagen debe ser unicamente de 281px de ancho x 373px de alto'
          - label: 'Tercera Palabra'
            name: 'palabra_3'
            widget: 'string'
            hint: 'es la Palabra que aparece debajo de la Palabra Común en la tercera tarjeta'
          - label: 'Tercera Frase'
            name: 'frase_3'
            widget: 'string'
            hint: 'es la frase que aparece en la parte baja de la tarjeta'
          - label: 'Tercera URL'
            name: 'url_3'
            widget: 'string'
            hint: 'es el enlace dentro de nuestra página al que lleva la tarjeta'
          - label: 'Cuarta Imagen'
            name: 'imagen4'
            widget: 'image'
            hint: 'El tamaño de la imagen debe ser unicamente de 281px de ancho x 373px de alto'
          - label: 'Cuarta Palabra'
            name: 'palabra_4'
            widget: 'string'
            hint: 'es la Palabra que aparece debajo de la Palabra Común en la cuarta tarjeta'
          - label: 'Cuarta Frase'
            name: 'frase_4'
            widget: 'string'
            hint: 'es la frase que aparece en la parte baja de la tarjeta'
          - label: 'Cuarta URL'
            name: 'url_4'
            widget: 'string'
            hint: 'es el enlace dentro de nuestra página al que lleva la tarjeta'
      - name: 'sociales'
        label: 'Publicaciones de Redes Sociales en pagina inicial'
        file: '_data/sociales.yml'
        fields: 
          - label: 'Publicación Instagram'
            name: 'instagram1'
            widget: 'string'
            hint: 'Utiliza lo que aparece al final de la URL en Instagram después de... instagram.com/p/... esa serie de caracteres.'
          - label: 'FanPage de Facebook'
            name: 'facebook'
            widget: 'string'
            hint: 'Ingresa la URL de la FanPage de Facebook'
          - label: 'Publicación Instagram 2'
            name: 'instagram2'
            widget: 'string'
            hint: 'Utiliza lo que aparece al final de la URL en Instagram después de... instagram.com/p/... esa serie de caracteres.'
  - name: 'acerca-de'
    label: 'Acerca de'
    description: 'Configuración de las páginas que se encuentran en el menú Acerca De donde aparecerá la Configuración de cada página'
    folder: "_acerca-de"
    create: true
    fields: 
      - name: 'layout'
        label: 'Layout'
        widget: 'hidden'
        default: 'acerca'
      - name: 'title'
        label: 'Titulo'
        widget: 'string'
      - name: 'resumen'
        label: 'Resumen'
        hint: 'Un breve resumen con menos de 140 caracteres sobre lo que trata esta Publicación'
      - name: 'cita'
        label: 'Cita de Autor'
        widget: 'string'
      - name: 'cita_autor'
        label: 'Autor de la Cita'
        widget: 'string'
        hint: 'Nombre del autor de la Cita utilizada anteriormente'
      - name: 'cita_img'
        label: 'Imagen del Autor Citado'
        widget: 'image'
      - name: 'video'
        label: 'Video de YouTube'
        widget: 'string'
        hint: 'Aquí debes colocar sólo el código del video, es decir, lo que aparece después de watch?v= '
      - name: 'img'
        label: 'Imagen del Articulo'
        widget: 'image'
        hint: 'Imagen principal del articulo la misma que se muestra al lado derecho en la parte superior del mismo.'
      - name: 'categories'
        label: 'Categorias'
        widget: 'hidden'
        default: 'acerca-de'
      - name: 'amp_components'
        label: 'Componentes de AMP'
        widget: 'list'
        default: '<script async custom-element="amp-instagram" src="https://cdn.ampproject.org/v0/amp-instagram-0.1.js"></script>'
        hint: 'NO UTILIZAR a menos que sepa para que sirve'
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
  - name: 'lo-que-hacemos'
    label: 'Lo que hacemos'
    description: 'Configuración de las páginas que se encuentran en el menú Lo que hacemos De donde aparecerá la Configuración de cada página'
    folder: "_lo-que-hacemos"
    create: true
    fields: 
      - name: 'layout'
        label: 'Layout'
        widget: 'hidden'
        default: 'hacemos'
      - name: 'title'
        label: 'Titulo'
        widget: 'string'
      - name: 'resumen'
        label: 'Resumen'
        hint: 'Un breve resumen con menos de 140 caracteres sobre lo que trata esta Publicación'
      - name: 'img'
        label: 'Imagen del Articulo'
        widget: 'image'
        hint: 'Imagen principal del articulo la misma que se muestra al lado derecho en la parte superior del mismo.'
      - name: 'instagram'
        label: 'Publicación de Instagram'
        widget: 'string'
        hint: 'Utiliza lo que aparece al final de la URL en Instagram después de... instagram.com/p/... esa serie de caracteres.'
      - name: 'categories'
        label: 'Categorias'
        widget: 'hidden'
        default: 'lo-que-hacemos'
      - name: 'amp_components'
        label: 'Componentes de AMP'
        widget: 'list'
        default: '<script async custom-element="amp-instagram" src="https://cdn.ampproject.org/v0/amp-instagram-0.1.js"></script>'
        hint: 'NO UTILIZAR a menos que sepa para que sirve'
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
  - name: 'unidades'
    label: 'Nuestras Unidades'
    description: 'Configuración de las páginas que se encuentran en el menú Nuestras Unidades de donde aparecerá la Configuración de cada página'
    folder: "_unidades"
    create: true
    fields: 
      - name: 'layout'
        label: 'Layout'
        widget: 'hidden'
        default: 'unidades'
      - name: 'title'
        label: 'Titulo'
        widget: 'string'
      - name: 'resumen'
        label: 'Resumen'
        hint: 'Un breve resumen con menos de 140 caracteres sobre lo que trata esta Publicación'
      - name: 'img'
        label: 'Imagen del Articulo'
        widget: 'image'
        hint: 'Imagen principal del articulo la misma que se muestra al lado derecho en la parte superior del mismo.'
      - name: 'svg'
        label: 'Insignia Insitucional de la unidad'
        widget: 'image'
        hint: 'Insignia o Logo que utiliza la Asociación de Guías y Scouts de Chile para representar a la unidad'
      - name: 'bandera'
        label: 'Bandera de la Unidad'
        widget: 'image'
        hint: 'Imagen de la Bandera de esta unidad'
      - name: 'instagram1'
        label: 'Publicación de Instagram 1'
        widget: 'string'
        hint: 'Una publicación de instagram sobre esta unidad, Utiliza lo que aparece al final de la URL en Instagram después de... instagram.com/p/... esa serie de caracteres.'
      - name: 'instagram2'
        label: 'Publicación de Instagram 2'
        widget: 'string'
        hint: 'Una publicación de instagram sobre esta unidad, Utiliza lo que aparece al final de la URL en Instagram después de... instagram.com/p/... esa serie de caracteres.'
      - name: 'categories'
        label: 'Categorias'
        widget: 'hidden'
        default: 'unidades'
      - name: 'amp_components'
        label: 'Componentes de AMP'
        widget: 'list'
        default: '<script async custom-element="amp-instagram" src="https://cdn.ampproject.org/v0/amp-instagram-0.1.js"></script>'
        hint: 'NO UTILIZAR a menos que sepa para que sirve'
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
  - name: 'posts'
    label: 'Noticias'
    description: 'Publicación de noticias y novedades del grupo'
    folder: "_posts"
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: 
      - name: 'layout'
        label: 'Layout'
        widget: 'hidden'
        default: 'posts'
      - name: 'title'
        label: 'Titulo'
        widget: 'string'
      - name: 'resumen'
        label: 'Resumen'
        hint: 'Un breve resumen con menos de 140 caracteres sobre lo que trata esta Publicación'
      - name: 'img'
        label: 'Imagen del Articulo'
        widget: 'image'
        hint: 'Imagen principal del articulo la misma que se muestra al lado derecho en la parte superior del mismo. la imagen debe ser de 300 x 300 px'
      - name: 'instagram'
        label: 'Publicación de Instagram'
        widget: 'string'
        hint: 'Una publicación de instagram sobre esta unidad, Utiliza lo que aparece al final de la URL en Instagram después de... instagram.com/p/... esa serie de caracteres.'
      - name: 'video'
        label: 'Video desde YouTube'
        widget: 'string'
        hint: 'Aquí debes colocar sólo el código del video, es decir, lo que aparece después de watch?v= '
      - name: 'categories'
        label: 'Categorias'
        widget: 'list'
        default: ['noticias']
        hint: 'separe cada categoría con una coma seguida de un espacio, para que la noticia también aparezca en la sección de cada unidad utilice el nombre de la unidad, por ejemplo: noticias, tropa'
      - name: 'amp_components'
        label: 'Componentes de AMP'
        widget: 'list'
        hint: 'NO UTILIZAR a menos que sepa para que sirve'
      - name: 'body'
        label: 'Body'
        widget: 'markdown'