backend:
  name: github
  repo: claudiomateluna/nua_mana
  branch: gh-pages

media_folder: 'assets/images/uploads'
logo_url: '/assets/images/brand.svg'

collections:
  - name: 'configuracion_general'
    label: 'Configuración General'
    description: 'Configuración general del sitio web, como su nombre, dirección fisica, Redes Sociales, etc.'
    files:
      - name: 'site'
        label: 'Sitio'
        file: '_data/site.yml'
        fields:
          - label: 'Titulo'
            name: 'titulo'
            widget: 'string'
            hint: 'Titulo del Sitio Web'
          - label: 'Nombre'
            name: 'nombre'
            widget: 'string'
            hint: 'Nombre del grupo Scout'
          - label: 'Dirección'
            name: 'address'
            widget: 'object'
            fields: 
              - label: 'Institución patrocinante'
                name: 'institution'
                widget: 'string'
                hint: 'Nombre de la institution patrocinante que alberga al grupo Scout'
              - label: 'Calle y Numeración'
                name: 'street'
                widget: 'string'
                hint: 'Nombre de la calle y la numeración donde se ubica el grupo'
              - label: 'Comuna'
                name: 'commune'
                widget: 'string'
                hint: 'Comuna donde se ubica el grupo Scout'
              - label: 'Ciudad'
                name: 'city'
                widget: 'string'
                hint: 'Ciudad donde se ubica el grupo Scout'
              - label: 'País'
                name: 'country'
                widget: 'string'
                hint: 'País donde se ubica el grupo Scout'
              - label: 'Código Postal'
                name: 'zip'
                widget: 'string'
          - label: 'Correo Electronico'
            name: 'email'
            widget: 'string'
            hint: 'Correo Electronico oficial del grupo Scout'
          - label: 'Telefono de Contacto'
            name: 'tel'
            widget: 'string'
            hint: 'Ingrese el número telefonico sin espacios con formato de whatsapp'
          - label: 'Telefono para mostrar'
            name: 'tel_display'
            widget: 'string'
            hint: 'Ingrese el número telefonico en formato fácil de leer y con espacios'
          - label: 'Descripción'
            name: 'descripcion'
            widget: 'string'
            hint: 'Descripción del sitio web del grupo Scout (esto es utilizado para SEO del sitio)'
          - label: 'Resumen General'
            name: 'resumen'
            widget: 'string'
            hint: 'resumen del sitio web (esto es utilizado para las publicaciones en redes sociales)'
          - label: 'Encabezado en Rongo rongo'
            name: 'encabezado_rongorongo'
            widget: 'string'
          - label: 'Frase Fuerza'
            name: 'frase_fuerza'
            widget: 'string'
          - label: 'encuentranos'
            name: 'encuentranos'
            widget: 'object'
            fields: 
              - label: 'Nuestro grupo trabaja en'
                name: 'nuestro_grupo_trabaja_en'
                widget: 'string'
                hint: 'Nombre de la institution patrocinante (utilizado en el mapa dentro de la pagina principal del sitio web)'
              - label: 'Ubicado en'
                name: 'ubicado_en'
                widget: 'string'
                hint: 'Dirección donde realiza sus actividades el grupo Scout (utilizado en el mapa dentro de la pagina principal del sitio web)'
              - label: 'Comuna de'
                name: 'comuna_de'
                widget: 'string'
                hint: 'Comuna donde realiza sus actividades el grupo Scout (utilizado en el mapa dentro de la pagina principal del sitio web)'
              - label: 'Nos encontraras todos los'
                name: 'nos_encontraras_todos_los'
                widget: 'string'
                hint: 'Indique el día y el horario en que comienzan las actividades (utilizado en el mapa dentro de la pagina principal del sitio web)'
          - label: 'Mapa'
            name: 'mapa'
            widget: 'string'
            hint: 'Llave de Google Maps para la ubicación'
          - label: 'Misión'
            name: 'mision'
            widget: 'markdown'