backend:
  name: github
  repo: claudiomateluna/nua_mana
  branch: gh-pages

media_folder: 'assets/images/uploads'
logo_url: '/assets/images/brand.svg'

collections:
  - name: 'configuracion_general'
    label: 'Configuración General'
    description: 'Configuración general del sitio web, como su nombre, dirección física, Redes Sociales, etc.'
    files:
      - name: 'site'
        label: 'Sitio'
        file: '_data/site.yml'
        fields:
          - label: 'Titulo'
            name: 'titulo'
            widget: 'string'
            hint: 'Titulo del Sitio Web'
          - label: 'Nombre'
            name: 'nombre'
            widget: 'string'
            hint: 'Nombre del grupo Scout'
          - label: 'Dirección'
            name: 'address'
            widget: 'object'
            fields: 
              - label: 'Institución patrocinante'
                name: 'institution'
                widget: 'string'
                hint: 'Nombre de la institución patrocinante que alberga al grupo Scout'
              - label: 'Calle y Numeración'
                name: 'street'
                widget: 'string'
                hint: 'Nombre de la calle y la numeración donde se ubica el grupo'
              - label: 'Comuna'
                name: 'commune'
                widget: 'string'
                hint: 'Comuna donde se ubica el grupo Scout'
              - label: 'Ciudad'
                name: 'city'
                widget: 'string'
                hint: 'Ciudad donde se ubica el grupo Scout'
              - label: 'País'
                name: 'country'
                widget: 'string'
                hint: 'País donde se ubica el grupo Scout'
              - label: 'Código Postal'
                name: 'zip'
                widget: 'string'
          - label: 'Correo Electrónico'
            name: 'email'
            widget: 'string'
            hint: 'Correo Electrónico oficial del grupo Scout'
          - label: 'Teléfono de Contacto'
            name: 'tel'
            widget: 'string'
            hint: 'Ingrese el número telefónico sin espacios con formato de whatsapp'
          - label: 'Teléfono para mostrar'
            name: 'tel_display'
            widget: 'string'
            hint: 'Ingrese el número telefónico en formato fácil de leer y con espacios'
          - label: 'Descripción'
            name: 'descripcion'
            widget: 'string'
            hint: 'Descripción del sitio web del grupo Scout (esto es utilizado para SEO del sitio)'
          - label: 'Resumen General'
            name: 'resumen'
            widget: 'string'
            hint: 'resumen del sitio web (esto es utilizado para las publicaciones en redes sociales)'
          - label: 'Encabezado en Rongo rongo'
            name: 'encabezado_rongorongo'
            widget: 'string'
          - label: 'Frase Fuerza'
            name: 'frase_fuerza'
            widget: 'string'
          - label: 'encuentranos'
            name: 'encuentranos'
            widget: 'object'
            fields: 
              - label: 'Nuestro grupo trabaja en'
                name: 'nuestro_grupo_trabaja_en'
                widget: 'string'
                hint: 'Nombre de la institución patrocinante (utilizado en el mapa dentro de la pagina principal del sitio web)'
              - label: 'Ubicado en'
                name: 'ubicado_en'
                widget: 'string'
                hint: 'Dirección donde realiza sus actividades el grupo Scout (utilizado en el mapa dentro de la pagina principal del sitio web)'
              - label: 'Comuna de'
                name: 'comuna_de'
                widget: 'string'
                hint: 'Comuna donde realiza sus actividades el grupo Scout (utilizado en el mapa dentro de la pagina principal del sitio web)'
              - label: 'Nos encontraras todos los'
                name: 'nos_encontraras_todos_los'
                widget: 'string'
                hint: 'Indique el día y el horario en que comienzan las actividades (utilizado en el mapa dentro de la pagina principal del sitio web)'
          - label: 'Mapa'
            name: 'mapa'
            widget: 'string'
            hint: 'Llave de Google Maps para la ubicación'
          - label: 'Misión'
            name: 'mision'
            widget: 'markdown'
          - label: 'Redes Sociales'
            name: 'redes_sociales'
            widget: 'object'
            fields: 
              - label: 'Twitter'
                name: 'twitter'
                widget: 'string'
                hint: 'Escriba la URL de la red social'
              - label: 'Facebook'
                name: 'facebook'
                widget: 'string'
                hint: 'Escriba la URL de la red social'
              - label: 'Google Plus'
                name: 'google_plus'
                widget: 'string'
                hint: 'Escriba la URL de la red social'
              - label: 'Instagram'
                name: 'instagram'
                widget: 'string'
                hint: 'Escriba la URL de la red social'
              - label: 'Whatsapp'
                name: 'whatsapp'
                widget: 'string'
                hint: 'Escriba el número principal de contacto sin espacios comenzando por +569'
      - name: 'carousel'
        label: 'Carousel de Fotografías'
        file: '_data/carousel.yml'
        fields: 
          - label: 'Logo'
            name: 'logo'
            widget: 'image'
          - label: 'Ancho del Logo'
            name: 'logo_w'
            widget: 'string'
          - label: 'Alto del Logo'
            name: 'logo_h'
            widget: 'string'
          - label: 'Información de la Imagen'
            name: 'logo_alt'
            widget: 'string'
          - label: 'Imagen 1'
            name: '1i'
            widget: 'image'
          - label: 'Ancho de la Imagen 1'
            name: '1w'
            widget: 'string'
          - label: 'Información de la Imagen 1'
            name: '1alt'
            widget: 'string'
          - label: 'Imagen 2'
            name: '2i'
            widget: 'image'
          - label: 'Ancho de la Imagen 2'
            name: '2w'
            widget: 'string'
          - label: 'Información de la Imagen 2'
            name: '2alt'
            widget: 'string'
          - label: 'Imagen 3'
            name: '3i'
            widget: 'image'
          - label: 'Ancho de la Imagen 3'
            name: '3w'
            widget: 'string'
          - label: 'Información de la Imagen 3'
            name: '3alt'
            widget: 'string'
          - label: 'Imagen 4'
            name: '4i'
            widget: 'image'
          - label: 'Ancho de la Imagen 4'
            name: '4w'
            widget: 'string'
          - label: 'Información de la Imagen 4'
            name: '4alt'
            widget: 'string'
          - label: 'Imagen 5'
            name: '5i'
            widget: 'image'
          - label: 'Ancho de la Imagen 5'
            name: '5w'
            widget: 'string'
          - label: 'Información de la Imagen 5'
            name: '5alt'
            widget: 'string'
          - label: 'Imagen 6'
            name: '6i'
            widget: 'image'
          - label: 'Ancho de la Imagen 6'
            name: '6w'
            widget: 'string'
          - label: 'Información de la Imagen 6'
            name: '6alt'
            widget: 'string'
          - label: 'Imagen 7'
            name: '7i'
            widget: 'image'
          - label: 'Ancho de la Imagen 7'
            name: '7w'
            widget: 'string'
          - label: 'Información de la Imagen 7'
            name: '7alt'
            widget: 'string'
      - name: 'nosotros'
        label: 'Tarjetas'
        file: '_data/nosotros.yml'
        fields: 
          - label: 'Frase Común'
            name: 'frase_comun'
            widget: 'string'